name: testC
on:
  push:
    branches-ignore:
      - 'feat-*'
    paths:
      - 'src/**'
      - './*.nimble'
      - 'tests/**'
  pull_request:
  workflow_dispatch:
env:
  nim-version: 'stable'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v4
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ env.nim-version }}
    - name: Test C backend
      run: nimble testC

